services:
  redis:
    image: redis:7
    container_name: redis-bot
    volumes:
      - redis_data:/data
    networks:
      - app-network

  alembic:
    build:
      context: ./
    container_name: alembic-bot
    command: alembic upgrade head
    restart: "no"
    env_file:
      - prod.env
    environment:
      DATABASE_URL: >
        postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@${DB_IP}:${DB_PORT}/${DB_NAME}
    networks:
      - app-network

  bot:
    build:
      context: ./
    container_name: bot-bot
    env_file:
      - prod.env
    depends_on:
      - redis
    networks:
      - app-network
    profiles:
      - with_bot

  fill_db:
    build:
      context: ./
    container_name: fill_db-bot
    command: python -m static.fill_db
    env_file:
      - prod.env
    depends_on:
      - redis
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  app-network:
    driver: bridge
